### ISSUE TITLE
Socket Environment - invalid command request hangs the framework

### ISSUE THREAD

**Issue by ferpasri** [iv4xr-project/iv4xrDemo#9]
**Issue**
If we send an invalid command through LabRecruitsEnvironment + SocketEnvironment, the framework seems to be "indefinitely?" waiting for a response.

**BufferedReader**
https://github.com/iv4xr-project/iv4xrDemo/blob/master/src/main/java/environments/SocketEnvironment.java
```
socket = new Socket(host, port);
reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
writer = new PrintWriter(socket.getOutputStream(), true);
```

```@Override
   protected Object sendCommand_(EnvOperation cmd) {
        // The Environment super class uses sendCommand_ to send the json object
        String json = (String) cmd.arg;
        switch (cmd.command) {
            case "debug":
                return debug(json);
            case "request":
                try {
                    // write to the socket
                    writer.println(json);
                    // read from the socket
                    // HERE: BufferedReader is waiting for a response, and the framework hangs
                    String response = reader.readLine(); 
                    return response;
                } catch (IOException ex) {
                    System.out.println("I/O error: " + ex.getMessage());
                    return null;
                }
        }
        throw new IllegalArgumentException();
    }
```

**Example to Reproduce**
1. Edit src/test/java/agents/SimpleInteractionTest.java
2. Before the agent executes his tactic, send an incorrect command
3. Run the test with JUnit
<img width="515" alt="not_existing_command" src="https://user-images.githubusercontent.com/32359126/86447106-228f4900-bd15-11ea-9424-c5835869581b.PNG">
<img width="557" alt="socket_waiting" src="https://user-images.githubusercontent.com/32359126/86447179-405cae00-bd15-11ea-9a07-996fd40afe83.PNG">

**Expected Response**
- SUT (LabRecruits) response ? : will send some "not valid" response
- Timeout ? : if the socket does not respond continue

**Timeout solution**
- Adding a timeout to the socket seems to solve the hang issue, but not sure if it is the best solution.

```
socket = new Socket(host, port);
// Add a max timeout to not to stay indefinitely waiting for an response
socket.setSoTimeout(5000);
reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
writer = new PrintWriter(socket.getOutputStream(), true);
```

**Comment by wooshrow** [comment]
Hi Fernando, this issue should now be fixed in v2.1. There might be some API changes that affect you when moving from 1.x to 2.1 though.
